config/routes.rb
Edf::Application.routes.draw do
  resources :votes

  root :to => 'votes#new'

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  attr_accessible :agglom, :culture, :diginf, :env, :finance, :inf, :lifestyle, :market, :name, :skills, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  # GET /votes
  # GET /votes.json
  def index
    @votes = Vote.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @votes }
    end
  end

  # GET /votes/1
  # GET /votes/1.json
  def show
    @vote = Vote.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vote }
    end
  end

  # GET /votes/new
  # GET /votes/new.json
  def new
    @vote = Vote.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vote }
    end
  end

  # GET /votes/1/edit
  def edit
    @vote = Vote.find(params[:id])
  end

  # POST /votes
  # POST /votes.json
  def create
    @vote = Vote.new(params[:vote])

    respond_to do |format|
      if @vote.save
        format.html { redirect_to @vote, notice: 'Vote was successfully created.' }
        format.json { render json: @vote, status: :created, location: @vote }
      else
        format.html { render action: "new" }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /votes/1
  # PUT /votes/1.json
  def update
    @vote = Vote.find(params[:id])

    respond_to do |format|
      if @vote.update_attributes(params[:vote])
        format.html { redirect_to @vote, notice: 'Vote was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /votes/1
  # DELETE /votes/1.json
  def destroy
    @vote = Vote.find(params[:id])
    @vote.destroy

    respond_to do |format|
      format.html { redirect_to votes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Edf</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/votes/_form.html.erb
<main class="cf"> 
  <div class="header">
    <img class="edf-logo" src="assets/european-digital-forum-logo.png"/>
  </div>
  <container class="sliders">
    <div  class="about-text">The European Digital Forum is a think tank dedicated to empowering web entrepreneurs and growing Europe’s digital economy. As part of our work e are creating the European Digital Readiness Index to measure how well different European cities are facilitating digital entrepreneurship. To help us create this index indicate on the sliders below how important you think the factors are for supporting digital entrepreneurship </div>
    <div class="category-container cf">
      <div class="label">Access to finance</div>
      <div class="slider" id="finance-slider"></div>
      <div id="finance" class="counter">50</div>
    </div>  
    <div class="category-container cf">
      <div class="label">Skills</div>
      <div class="slider" id="skills-slider"></div>
      <div id="skills" class="counter">50</div>
    </div>  
    <div class="category-container cf">
      <div class="label">Business Environment</div>
      <div class="slider" id="env-slider"></div>
      <div id="env" class="counter">50</div>
     </div> 
    <div class="category-container cf">
      <div class="label">Entrepreneurial Culture</div>
      <div class="slider" id="culture-slider"></div>
      <div id="culture" class="counter">50</div>
    </div>
    <div class="category-container cf">
      <div class="label">Physical Infrastructure</div>
      <div class="slider" id="inf-slider"></div>
      <div id="inf" class="counter">50</div>
    </div>
    <div class="category-container cf">
      <div class="label">Digital Infrastructure</div>
      <div class="slider" id="diginf-slider"></div> 
      <div id="diginf" class="counter">50</div>
    </div>
    <div class="category-container cf">
      <div class="label">Agglomeration Effects</div>
      <div class="slider" id="agglom-slider"></div>
      <div id="agglom" class="counter">50</div>
    </div>
    <div class="category-container cf">
      <div class="label">Market Conditions</div>
      <div class="slider" id="market-slider"></div>
      <div id="market" class="counter">50</div>
    </div>
    <div class="category-container cf">
      <div class="label">Lifestyle</div>
      <div class="slider" id="lifestyle-slider"></div>
      <div id="lifestyle" class="counter">50</div>
    </div>
    <div class="submit-vote">SUBMIT YOUR CHOICE</div>
    <div class="success-notice"></div>
  </container>
</main>

app/views/votes/edit.html.erb
<h1>Editing vote</h1>

<%= render 'form' %>

<%= link_to 'Show', @vote %> |
<%= link_to 'Back', votes_path %>

app/views/votes/index.html.erb
<h1>Listing votes</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Title</th>
    <th>Finance</th>
    <th>Skills</th>
    <th>Env</th>
    <th>Culture</th>
    <th>Inf</th>
    <th>Diginf</th>
    <th>Agglom</th>
    <th>Market</th>
    <th>Lifestyle</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @votes.each do |vote| %>
  <tr>
    <td><%= vote.name %></td>
    <td><%= vote.title %></td>
    <td><%= vote.finance %></td>
    <td><%= vote.skills %></td>
    <td><%= vote.env %></td>
    <td><%= vote.culture %></td>
    <td><%= vote.inf %></td>
    <td><%= vote.diginf %></td>
    <td><%= vote.agglom %></td>
    <td><%= vote.market %></td>
    <td><%= vote.lifestyle %></td>
    <td><%= link_to 'Show', vote %></td>
    <td><%= link_to 'Edit', edit_vote_path(vote) %></td>
    <td><%= link_to 'Destroy', vote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Vote', new_vote_path %>

app/views/votes/new.html.erb
<%= render 'form' %>

<%#= link_to 'Back', votes_path %>

app/views/votes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @vote.name %>
</p>

<p>
  <b>Title:</b>
  <%= @vote.title %>
</p>

<p>
  <b>Finance:</b>
  <%= @vote.finance %>
</p>

<p>
  <b>Skills:</b>
  <%= @vote.skills %>
</p>

<p>
  <b>Env:</b>
  <%= @vote.env %>
</p>

<p>
  <b>Culture:</b>
  <%= @vote.culture %>
</p>

<p>
  <b>Inf:</b>
  <%= @vote.inf %>
</p>

<p>
  <b>Diginf:</b>
  <%= @vote.diginf %>
</p>

<p>
  <b>Agglom:</b>
  <%= @vote.agglom %>
</p>

<p>
  <b>Market:</b>
  <%= @vote.market %>
</p>

<p>
  <b>Lifestyle:</b>
  <%= @vote.lifestyle %>
</p>


<%= link_to 'Edit', edit_vote_path(@vote) %> |
<%= link_to 'Back', votes_path %>